# config ref https://docs.helix-editor.com/master/configuration.html
# https://github.com/helix-editor/helix/wiki/FAQ
# Smooth scrolling currently not supported: see https://github.com/helix-editor/helix/issues/1671
# https://helix-editor.com/news/release-22-03-highlights/

theme = "nord"

[editor]
mouse = false
true-color = true
shell=["bash", "-c"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.lsp]
display-messages=true

[keys]
[keys.normal]
# map `0` need this PR https://github.com/helix-editor/helix/pull/2174
"0"="goto_line_start"
"$"="goto_line_end"
# K is default to "keep_selections", I do not know what does this mean
"K" = "hover"

[keys.insert]
j = { k = "normal_mode" }

