# hcl https://github.com/helix-editor/helix/blob/35d2693630a4ec29a654704bc4be47badb8d6070/languages.toml#L992
[[language]]
name = "hcl"
language-server = { command = "nomad-lsp", args = [] }


[[language]]
name = "lua"
roots = [".luarc.json", ".luacheckrc", ".stylua.toml", "selene.toml",".git"]
#language-server = { command = "luahelper-lsp", args = ["-mode", "1", "-logflag", "1"] }
language-server = { command = "lua-language-server"}
# ref https://github.com/neovim/nvim-lspconfig/blob/master/lua/lspconfig/server_configurations/sumneko_lua.lua
# https://github.com/neovim/nvim-lspconfig/blob/master/doc/server_configurations.md#sumneko_lua
# https://learnxinyminutes.com/docs/toml/
config = {"telemetry" = { "enable" = false }}

[[language]]
name = "php"
# https://github.com/bmewburn/intelephense-docs/blob/master/installation.md#initialisation-options
# telemetry host: dc.services.visualstudio.com
#config = { "intelephense" = { "licenceKey" = "xxx", "telemetry" = { "enabled" = false }}}
config = { "licenceKey" = "xxx", "telemetry" = { "enabled" = false }}

## custom formatter (has higher priority than lsp formatter)
[[language]]
name = "hcl"
auto-format = true
formatter = { command = "hclfmt" , args = ["--"] }

[[language]]
name = "protobuf"
auto-format = true
# -- https://clang.llvm.org/docs/ClangFormatStyleOptions.html
# -- helix will auto quote the param, so we do not need to worry shell will parse `{}`
formatter = { command = "clang-format" , args = ["--style", "{ IndentWidth: 4, BasedOnStyle: google, AlignConsecutiveAssignments: true,  AlignConsecutiveDeclarations: true, ColumnLimit: 160 }"] }

#[[language]]
#name = "gomod"
#scope = "source.gomod"
#file-types = ["go.mod"]
#roots = ["go.mod"]
#diagnostic-severity = "Hint"
#auto-format = true
#comment-token = "//"
#language-server = { command = "gopls" }
#indent = { tab-width = 4, unit = "\t" }
#grammar = "gomod"
#
#[[grammar]]
#name = "gomod"
#source = { path = "/home/ttys3/repo/rust/tree-sitter-go-mod" }


